name: FoodDelivery

on:
  push:
    branches:
      - forOKFKS
  pull_request:
    branches:
      - forOKFKS

jobs:
  CheckErrors:
    runs-on: windows-latest

    steps:
    - name: Download Code
      uses: actions/checkout@v2

    - name: Download .Net
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore Nuget
      run: nuget restore FoodDelivery.sln

    - name: Build project
      run: |
        msbuild FoodDelivery.sln /p:Configuration=Release

    - name: Code Analysys
      run: |
        msbuild FoodDelivery.sln /p:Configuration=Release /p:RunCodeAnalysis=true