name: Build, Test, and Lint

on:
  push:
    branches:
      - kursach7

jobs:
  BuildAndTest:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore OrgManagmentApp.sln

    - name: Build Project
      run: dotnet build OrgManagmentApp.sln -c Release

    - name: Run Tests
      run: dotnet test OrgManagmentApp.sln -c Release

  LintCode:
    runs-on: ubuntu-latest
    needs: BuildAndTest # Выполняется после успешного выполнения BuildAndTest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: kursach7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true
        VALIDATE_CSHARP: true
        VALIDATE_YAML: true
        VALIDATE_JSON: true
        VALIDATE_XML: true
