name: Lint Code

on:
  push:
    branches:
      - kursach7

jobs:
  Lint:
    runs-on: ubuntu-latest # Super Linter работает только на Linux

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Super Linter
      uses: github/super-linter@v4
      env:
        DEFAULT_BRANCH: kursach7
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_ALL_CODEBASE: true # Проверяет весь код
        VALIDATE_CSHARP: true       # Включает проверку C#
        VALIDATE_XML: true          # Включает проверку XAML (как XML)
        DISABLE_LINTERS: 'ALL'      # Отключает все линтеры, кроме указанных выше
